apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 annotations:
 name: node-example
 namespace: default
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
  apiVersion: extensions/v1
  kind: Deployment
  name: node-example
 targetCPUUtilizationPercentage: 1
